package com.skylex_chess_clock.chessclock

const val TIME_RESULT_KEY = "TIME RESULT KEY"
const val INCREMENT_RESULT_KEY = "INCREMENT RESULT KEY"
const val CLOCK_MODE_RESULT_KEY = "CLOCK MODE RESULT KEY"

// SHARED PREFERENCES KEYS
const val PREFERENCE_KEY = "APP_PREFERENCE_KEY"
const val TIME_HELPER_PREFERENCE_KEY = "TIME_HELPER_PREFERENCE_KEY"
const val TIME_INCREMENT_PREFERENCE_KEY = "TIME_INCREMENT_PREFERENCE_KEY"
const val CLOCK_MODE_PREFERENCE_KEY = "CLOCK_MODE_PREFERENCE_KEY"